export const rjvThemes = [
  { label: "Apathy", value: "apathy" },
  { label: "Apathy (Inverted)", value: "apathy:inverted" },
  { label: "Ashes", value: "ashes" },
  { label: "Bespin", value: "bespin" },
  { label: "Brewer", value: "brewer" },
  { label: "Bright (Inverted)", value: "bright:inverted" },
  { label: "Bright", value: "bright" },
  { label: "Chalk", value: "chalk" },
  { label: "CodeSchool", value: "codeschool" },
  { label: "Colors", value: "colors" },
  { label: "Eighties", value: "eighties" },
  { label: "Embers", value: "embers" },
  { label: "Flat", value: "flat" },
  { label: "Google", value: "google" },
  { label: "Grayscale", value: "grayscale" },
  { label: "Grayscale (Inverted)", value: "grayscale:inverted" },
  { label: "Green Screen", value: "greenscreen" },
  { label: "Harmonic", value: "harmonic" },
  { label: "Hopscotch", value: "hopscotch" },
  { label: "Isotope", value: "isotope" },
  { label: "Marrakesh", value: "marrakesh" },
  { label: "Mocha", value: "mocha" },
  { label: "Monokai", value: "monokai" },
  { label: "Ocean", value: "ocean" },
  { label: "Paraiso", value: "paraiso" },
  { label: "Pop", value: "pop" },
  { label: "Railscasts", value: "railscasts" },
  { label: "RJV Default", value: "rjv-default" },
  { label: "Shapeshifter", value: "shapeshifter" },
  { label: "Shapeshifter (Inverted)", value: "shapeshifter:inverted" },
  { label: "Solarized", value: "solarized" },
  { label: "Summerfruit", value: "summerfruit" },
  { label: "Summerfruit (Inverted)", value: "summerfruit:inverted" },
  { label: "3024", value: "threezerotwofour" },
  { label: "Tomorrow", value: "tomorrow" },
  { label: "Tube", value: "tube" },
  { label: "Twilight", value: "twilight" },
];
